repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        stages:
          - commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        types:
          - c++
          - c
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        exclude: tests/
        types:
          - python
        args:
          - --rcfile
          - code/pyproject.toml
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        args:
          - -c
          - code/pyproject.toml
        exclude: tests/
        types:
          - python
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        args:
          - --project
          - code/
        language: node
        types:
          - python
        pass_filenames: false
        additional_dependencies:
          - pyright
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports
  - repo: local
    hooks:
      - id: latex-format-all
        name: latex-format-all
        entry: latex-format-all
        language: system
        types:
          - tex
  # - repo: https://github.com/amperser/proselint
  #   rev: 0.13.0
  #   hooks:
  #     - id: proselint
  #       types:
  #         - tex
