version: "3.7"
services:
  classifier:
    image: extgit.iaik.tugraz.at:8443/crypto_students/2020_bachelor_waldert/classifier
    restart: unless-stopped
    build:
      context: ./classifier
      dockerfile: classifier.Dockerfile

  backend:
    image: extgit.iaik.tugraz.at:8443/crypto_students/2020_bachelor_waldert/djangoapp
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    environment:
      SECRETS_FILE: "/run/secrets/fheclassifier_secrets"
      FHECLASSIFIER_PASSWORD_FILE: "/run/secrets/fheclassifier_password"
    secrets:
      - fheclassifier_secrets
      - fheclassifier_password
    volumes:
      - fheclassifierstatic:/var/resources/static/
      - fheclassifiermedia:/var/resources/media/
    depends_on:
      - backend_initialization

  frontend:
    image: extgit.iaik.tugraz.at:8443/crypto_students/2020_bachelor_waldert/nginx
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - fheclassifierstatic:/web/static/
      - fheclassifiermedia:/web/media/
    depends_on:
      - backend
    secrets:
      - ssl_certificate
      - ssl_privatekey

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - fheclassifierdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fheclassifierdb
      POSTGRES_USER: fheclassifier
      POSTGRES_PASSWORD_FILE: /run/secrets/fheclassifier_password
    secrets:
      - fheclassifier_password

  backend_initialization:
    image: extgit.iaik.tugraz.at:8443/crypto_students/2020_bachelor_waldert/djangoapp
    command: /app/init.sh
    restart: "no"
    depends_on:
      - db
    environment:
      SECRETS_FILE: "/run/secrets/fheclassifier_secrets"
      FHECLASSIFIER_PASSWORD_FILE: "/run/secrets/fheclassifier_password"
    secrets:
      - fheclassifier_secrets
      - fheclassifier_password
    volumes:
      - fheclassifierstatic:/var/resources/static/
      - fheclassifiermedia:/var/resources/media/

volumes:
  fheclassifierdb:
  fheclassifierstatic:
  fheclassifiermedia:

secrets:
  fheclassifier_password:
    file: "${SECRETS_DIR}/fheclassifier-password.txt"
  fheclassifier_secrets:
    file: "${SECRETS_DIR}/secrets.json"
  ssl_certificate:
    file: "${SECRETS_DIR}/fhe-classifier.cert"
  ssl_privatekey:
    file: "${SECRETS_DIR}/fhe-classifier.key"

