version: "3.7"
services:
  classifier:
    image: extgit.iaik.tugraz.at:8443/crypto_students/2020_bachelor_waldert/classifier
    restart: unless-stopped
    build:
      context: .
      dockerfile: classifier/classifier.Dockerfile

  frontend:
    image: extgit.iaik.tugraz.at:8443/crypto_students/2020_bachelor_waldert/nginx
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
      - 443:443
    secrets:
      - ssl_certificate
      - ssl_privatekey

secrets:
  ssl_certificate:
    file: "${SECRETS_DIR}/fhe-classifier.cert"
  ssl_privatekey:
    file: "${SECRETS_DIR}/fhe-classifier.key"
