version: "3.7"
services:
  classifier:
    image: mrp001/sealed-mnist-classifier
    restart: unless-stopped
    build:
      context: .
      dockerfile: classifier/classifier.Dockerfile

  frontend:
    image: mrp001/sealed-mnist-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./secrets/:/etc/secrets/
